name: Compilar APK Cami Parental 🌸

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Android SDK
      uses: android-actions/setup-android@v3

    - name: Configurar Gradle Oficial
      uses: gradle/actions/setup-gradle@v3

    - name: Compilar APK
      working-directory: ./android
      run: gradle assembleDebug --no-daemon

    - name: Subir APK como Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: CamiParental-APK
        path: android/app/build/outputs/apk/debug/*.apk
